/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Mockup theme colors
        "primary-container": "#8083ff",
        "error": "#ffb4ab",
        "primary": "#c0c1ff",
        "on-tertiary": "#3f008e",
        "surface-container-high": "#272a2f",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-fixed-dim": "#d2bbff",
        "on-background": "#e0e2e8",
        "secondary-fixed-dim": "#a4c9ff",
        "on-secondary": "#00315d",
        "on-primary-container": "#0d0096",
        "on-surface-variant": "#c7c4d7",
        "on-secondary-fixed-variant": "#004883",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#a476ff",
        "error-container": "#93000a",
        "glass-border": "rgba(255, 255, 255, 0.1)",
        "tertiary-fixed": "#eaddff",
        "on-primary-fixed": "#07006c",
        "surface-panel": "rgba(255, 255, 255, 0.03)",
        "secondary-fixed": "#d4e3ff",
        "inverse-on-surface": "#2d3135",
        "surface-bright": "#36393e",
        "on-surface": "#e0e2e8",
        "on-tertiary-fixed": "#25005a",
        "inverse-surface": "#e0e2e8",
        "engine-red": "#dc2626",
        "surface-container": "#1c2024",
        "inverse-primary": "#494bd6",
        "surface-tint": "#c0c1ff",
        "on-tertiary-fixed-variant": "#5a00c6",
        "outline-variant": "#464554",
        "on-primary": "#1000a9",
        "secondary": "#a4c9ff",
        "background": "#101418",
        "surface": "#101418",
        "surface-container-highest": "#32353a",
        "outline": "#908fa0",
        "surface-variant": "#32353a",
        "surface-container-lowest": "#0b0e13",
        "surface-deep": "#071A35",
        "surface-dim": "#101418",
        "tertiary": "#d2bbff",
        "secondary-container": "#0267b8",
        "on-secondary-fixed": "#001c39",
        "accent-glow": "rgba(180, 197, 255, 0.3)",
        "on-secondary-container": "#d6e5ff",
        "primary-fixed": "#e1e0ff",
        "on-error": "#690005",
        "on-tertiary-container": "#36007d",
        "surface-container-low": "#181c20",

        // Existing project colors
        cm: {
          bg:         '#F2F2F2',
          card:       '#FFFFFF',
          card2:      '#FAFAFA',
          accent:     '#B8860B',
          'accent-l': '#D4A017',
          'accent-d': '#8B6508',
          text:       '#111111',
          muted:      '#6B7280',
          border:     '#E2E2E2',
          'border-l': '#C8C8C8',
          success:    '#166534',
          warn:       '#92400E',
          nav:        '#131921',
          'nav-text': '#FFFFFF',
        },
      },
      borderRadius: {
        "custom": "28px"
      },
      spacing: {
        "unit": "8px",
        "section-gap": "160px",
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        "gutter": "32px",
        "container-max": "1440px"
      },
      fontFamily: {
        // Project fonts
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        sans:  ['"DM Sans"', 'system-ui', 'sans-serif'],
        mono:  ['"JetBrains Mono"', 'monospace'],
        // Mockup fonts
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"]
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        // Mockup font sizes
        "headline-md": ["24px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "500" }]
      },
      animation: {
        'fade-in':    'fadeIn 0.25s ease-out forwards',
        'slide-up':   'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slideDown 0.25s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer':    'shimmer 2s infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:   { from: { transform: 'translateY(12px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        slideDown: { from: { transform: 'translateY(-8px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        shimmer:   { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      screens: { 'xs': '375px' },
      boxShadow: {
        'card':      '0 1px 4px rgba(0,0,0,0.08), 0 0 0 1px rgba(0,0,0,0.04)',
        'card-hover':'0 4px 12px rgba(0,0,0,0.12), 0 0 0 1px rgba(0,0,0,0.06)',
        'accent-sm': '0 2px 8px rgba(184,134,11,0.2)',
      },
    },
  },
  plugins: [],
};
